#!/usr/bin/env python3
"""Extract Transvoxel transition cell tables from transvoxel-data npm package."""

import re

JS_PATH = r"C:\Users\Sonderan\AppData\Local\Temp\package\transvoxel-cjs.js"
OUT_PATH = r"C:\Users\Sonderan\AppData\Local\Temp\transition_table_data.rs"

with open(JS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

# Helper: extract array of numbers between `const NAME = [` and `];`
def extract_array(name, content):
    """Find `const NAME = [` ... `];` and return list of ints."""
    pattern = r'const ' + re.escape(name) + r' = \[([\s\S]*?)\n\];'
    match = re.search(pattern, content)
    assert match, f"Could not find {name}"
    text = match.group(1)
    # Remove comments
    text = re.sub(r'//.*', '', text)
    nums = [int(x.strip()) for x in text.replace('\n', '').split(',') if x.strip()]
    return nums

# 1. TRANSITION_CELL_CLASS: [u8; 512]
cell_class = extract_array('transitionCellClass', content)
assert len(cell_class) == 512, f"Expected 512, got {len(cell_class)}"

# 2. TRANSITION_CORNER_DATA
corner_data = extract_array('transitionCornerData', content)

# 3. TRANSITION_VERTEX_DATA: [[u16; 12]; 512]
# Each row: [val1, val2, ...] — variable length, pad to 12
match = re.search(r'const transitionVertexData = \[([\s\S]*?)\n\];', content)
assert match, "Could not find transitionVertexData"
vd_text = match.group(1)
rows = re.findall(r'\[([^\]]*)\]', vd_text)
vertex_data = []
for row_text in rows:
    vals = [int(x.strip()) for x in row_text.split(',') if x.strip()]
    while len(vals) < 12:
        vals.append(0)
    assert len(vals) == 12, f"Row has {len(vals)} values"
    vertex_data.append(vals)
assert len(vertex_data) == 512, f"Expected 512, got {len(vertex_data)}"

# 4. TRANSITION_CELL_DATA: 56 equivalence classes
# Format: new TransitionCellData(N, new Uint8Array([...])),
match = re.search(r'const transitionCellData = \[([\s\S]*?)\n\];', content)
assert match, "Could not find transitionCellData"
cd_text = match.group(1)
entries = re.findall(r'new TransitionCellData\((\d+),\s*new Uint8Array\(\[([^\]]*)\]\)\)', cd_text)
cell_data_counts = []
cell_data_indices = []
for geom, indices_text in entries:
    counts = int(geom)
    indices = [int(x.strip()) for x in indices_text.split(',') if x.strip()]
    cell_data_counts.append(counts)
    cell_data_indices.append(indices)
assert len(cell_data_counts) == 56, f"Expected 56, got {len(cell_data_counts)}"

# ── Generate Rust source ──────────────────

out = []
out.append('//! Auto-generated Transvoxel transition cell lookup tables.')
out.append('//! Source: transvoxel-data npm package v1.0.3 (MIT/Apache 2.0),')
out.append("//! derived from Eric Lengyel's Transvoxel Algorithm reference implementation.")
out.append('//! Generated by tools/extract_tables.py — do not edit manually.')
out.append('')

# TRANSITION_CELL_CLASS: [u8; 512]
out.append('pub(crate) static TRANSITION_CELL_CLASS: [u8; 512] = [')
for i in range(0, 512, 16):
    line = '    ' + ', '.join(f'{v:3}' for v in cell_class[i:i+16]) + ','
    out.append(line)
out.append('];')
out.append('')

# TRANSITION_VERTEX_DATA: [[u16; 12]; 512]
out.append('pub(crate) static TRANSITION_VERTEX_DATA: [[u16; 12]; 512] = [')
for row in vertex_data:
    line = '    [' + ', '.join(f'{v:5}' for v in row) + '],'
    out.append(line)
out.append('];')
out.append('')

# TRANSITION_CELL_DATA_COUNTS: [u8; 56]
out.append('pub(crate) static TRANSITION_CELL_DATA_COUNTS: [u8; 56] = [')
out.append('    ' + ', '.join(f'{v:3}' for v in cell_data_counts))
out.append('];')
out.append('')

# TRANSITION_CELL_INDICES — flat with length prefix per class
flat = []
offsets = []
for indices in cell_data_indices:
    offsets.append(len(flat))
    flat.append(len(indices))  # length prefix
    flat.extend(indices)

out.append(f'pub(crate) static TRANSITION_CELL_OFFSETS: [u16; 56] = [')
out.append('    ' + ', '.join(f'{v:4}' for v in offsets))
out.append('];')
out.append('')

out.append(f'pub(crate) static TRANSITION_CELL_INDICES: [u8; {len(flat)}] = [')
for i in range(0, len(flat), 24):
    line = '    ' + ', '.join(f'{v:3}' for v in flat[i:i+24]) + ','
    out.append(line)
out.append('];')
out.append('')

# TRANSITION_CORNER_DATA: [u8; N]
out.append(f'pub(crate) static TRANSITION_CORNER_DATA: [u8; {len(corner_data)}] = [')
for i in range(0, len(corner_data), 24):
    line = '    ' + ', '.join(f'{v:3}' for v in corner_data[i:i+24]) + ','
    out.append(line)
out.append('];')

result = '\n'.join(out)
with open(OUT_PATH, 'w', encoding='utf-8') as f:
    f.write(result)

print(f"SUCCESS: {len(result.splitlines())} lines written to {OUT_PATH}")
print(f"  TRANSITION_CELL_CLASS: {len(cell_class)} entries")
print(f"  TRANSITION_VERTEX_DATA: {len(vertex_data)} rows x {len(vertex_data[0])} cols")
print(f"  TRANSITION_CELL_DATA: {len(cell_data_counts)} classes, {sum(len(x) for x in cell_data_indices)} total indices")
print(f"  TRANSITION_CORNER_DATA: {len(corner_data)} entries")
